name: flutter_allroundrefresh_example
description: Demonstrates how to use the flutter_allroundrefresh plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ####
  cupertino_icons: ^0.1.2
  http: 0.12.0
  dio: ^2.1.13
  cached_network_image: ^0.8.0
  ####

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_allroundrefresh:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/